CREATE TABLE user_authentication` (
  `KEY` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` NVARCHAR(200) NOT NULL,
  `PASSWORD` NVARCHAR(100) NOT NULL,
  `LAST_LOGIN_DATE` DATETIME NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(45) NULL,
  `MODIFIED_DATE` DATETIME NULL,
  `MODIFIED_BY` VARCHAR(45) NULL,
  PRIMARY KEY (`KEY`),
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC));