/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class KafkaTopicsProducerTest {
  @Test
  public void testSomeLibraryMethod() {
    KafkaTopicsProducer classUnderTest = new KafkaTopicsProducer();
    // assertTrue("someLibraryMethod should return 'true'", classUnderTest.produceTopics(null));
  }
}
